spring.application.name=react-spring-ecomm

spring.datasource.url=jdbc:mysql://localhost:3306/E_commerce
spring.datasource.username=root
spring.datasource.password=Jaideep@2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# EMAIL CONFIGURATION
# ===============================

# ===============================
# EMAIL CONFIGURATION (FIXED)
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=sabbarapujaideep@gmail.com
spring.mail.password=vwdj ihot epuc lolb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Important SSL trust fixes
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.main.banner-mode=off





